In [ ]:
!pip install numpy

In [2]:
import numpy as np

#  **THE BASICS**

- `.ndim` to know the dimensions 
- `.size` to know the size of the array
- `.dtype` to know the data type of the array element
- `.itemsize` to know the Byte size of the element
- `.nbytes` to know the total memorysize

we can set the data type using `dtype="int8,int16,....int256"` in terms of bits


In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
b=np.array([[1,2,3],[4,5,6]],dtype='int32')
print(b.ndim)
print(b.size)
print(b.dtype)
print(f"{b.itemsize}" +' bytes') # depends upon the decliared size 
print(b.nbytes)

2
6
int32
4 bytes
24


#  **Access and Manipulating**

- `array[r,c]` to access particular element - allows indexing and negative indexing
- `array[:,c]` `array[r,:]` allows to select c column and r row respectively
- `s:e:st` this alows to slice selected part s=start, e=end-1,st=step
- once we acccess the element we can manipuate it `array[r,c]=x`
- we can assign using slice method too `array[s:e,c]=[s,.,.,e]`
- elements can be accessed from `OUTSIDE to INSIDE` with ` , ` separated.
[ND Code](#Multiple-Dimenssion)


In [16]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a.shape)
print(a)

(2, 7)
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
a[1,4]

12

In [20]:
a[:,1] # this shows the 2nd column

array([2, 9])

In [24]:
a[1,:4:2] # this  shows the 2nd row
# start at 0 end at 3 every 2nd number (8  9 10 11 12 13 14)
#8,10

array([ 8, 10])

In [25]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
print(a[1,5])
a[1,5]=15
print(a[1,5])
a

15
15


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 15, 14]])

In [30]:
a[0,2:5]=[99,98,97]
a

array([[ 1,  2, 99, 98, 97,  6,  7],
       [ 8,  9, 10, 11, 12, 15, 14]])

### Multiple Dimenssion

In [35]:
b=np.array([[[1,2,3,4],[5,6,7,8]],[[4,7,8,9],[10,11,14,56]],[[5,6,7,8],[17,18,19,20]]])
b
# I want to change 56 to 108 out to in approach
print(b.shape)
b[1,1,3]

(3, 2, 4)


56